version: '3'

services:
  mongodb:
    ports:
      - 27017:27017
    container_name: mongodb-test
    image: mongo
    networks:
      - testnet
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data/mongo:/data/db
      - ./logs:/data/logs

networks:
  testnet:
    driver: bridge
